### ISSUE TITLE
Bug: LOTS of setup errors

### ISSUE THREAD

**Issue by Laxystem** [bonfire-networks/bonfire-app#1060]
I've tried with 0.9.10-beta.170, .165, and 169.

After cloning, I execute `mix deps.get`. It goes fine. Then, `just config`. There's an error.
<details><summary>`just config` results</summary>
<p>

```
Switching to flavour 'classic' in dev env...
cd config && (find ../extensions/bonfire/ -type f -name "deps.*" -exec ln -sfn {} ./ \; || find ../deps/bonfire/ -type f -name "deps.*" -exec ln -sfn {} ./ \; || echo "Could not symlink the bonfire deps") && ls -la ./
find: ‘../extensions/bonfire/’: No such file or directory
total 144
drwxr-xr-x. 1 ~ ~ 1108 Oct 29 18:16 .
# trimmed my username to not doxx myself --- why is it in the logs???
Using flavour 'classic' at flavours/classic with env 'dev' with vars from ./flavours/classic/config/dev/.env 

Now make sure to finish the flavour setup with 'just setup-dev'. You can also edit your config for flavour 'classic' in /.env and ./config/ more generally.
```
</p>
</details> 
Then, `just setup-dev`. Not only I get more warnings than my terminal's maximum capacity, I also get this:

```

== Compilation error in file lib/components/extensions/view_code_live.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.16.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.16.3) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.16.3) lib/enum.ex:4396: Enum.reduce/3
    (surface 0.12.0) lib/surface/base_component.ex:184: Surface.BaseComponent.signature_func/1
    (surface 0.12.0) expanding macro: Surface.BaseComponent.__before_compile__/1
    lib/components/extensions/view_code_live.ex:1: Bonfire.UI.Common.ViewCodeLive (module)
could not compile dependency :bonfire_ui_common, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile bonfire_ui_common --force", update it with "mix deps.update bonfire_ui_common" or clean it with "mix deps.clean bonfire_ui_common"
error: Recipe `cmd` failed on line 844 with exit code 1
error: Recipe `mix` failed on line 878 with exit code 1
error: Recipe `_ext-migrations-copy` failed on line 157 with exit code 1
error: Recipe `extension-post-install` failed on line 154 with exit code 1
error: Recipe `deps-fetch` failed on line 369 with exit code 1
error: Recipe `setup-dev` failed on line 151 with exit code 1
```

And that's without mentioning I had to create my own script with trial-and-error to clone and setup bonfire, because the documentation is utterly horrendous.

**Comment by ivanminutillo** [comment]
Closing this issue as it violates the [Bonfire Code of Conduct](https://bonfirenetworks.org/conduct/)

**Comment by Laxystem** [comment]
> Closing this issue as it violates the [Bonfire Code of Conduct](https://bonfirenetworks.org/conduct/)

violates, how?
