### ISSUE TITLE
Manually test federation across bonfire and other fediverse servers

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#126]
- [x] #768
- [x] Misskey/etc
- [x] Pixelfed
- [x] Akomma
- [x] GoToSocial
- [x] Peertube
- [x] Mobilizon
- [x] Lemmy
- [x] kbin
- [x] piefed
- [ ] WriteFreely
- [ ] Wordpress
- [ ] Plume
- [x] Castopod
- [ ] Funkwhale
- [ ] Owncast
- [ ] BookWyrm
- [ ] Takahē
- [ ] Etc

---

See spreadsheet at https://docs.google.com/spreadsheets/d/1UPBpzc3KS-290HZkE7Vz9RQ-grNXbF3Z1Nj9hJQ9EsI/edit#gid=0

---

- [x] #868

**Comment by mayel** [comment]
Both test suites are down. I've pinged their maintainers.

**Comment by mayel** [comment]
I've refactored the AP lib so that we're able to run tests from within bonfire (which means with the real Repo and Adapter, so catching more integration issues) and fixed lots of small things along the way so all tests are passing:
- AP library: 84 tests, 0 failures
- bonfire_federate_activitypub/test/activity_pub_integration: 25 tests, 0 failures

Next is writing more tests for some issues I found while trying real world federation: https://notes.zo.team/cEdeR1nAQ9q-HGr0vgfT4w?view

**Comment by mayel** [comment]
# WIP Federation testing

See spreadsheet at https://docs.google.com/spreadsheets/d/1UPBpzc3KS-290HZkE7Vz9RQ-grNXbF3Z1Nj9hJQ9EsI/edit#gid=0

## not working:
- [ ] dunno if following between 2 bonfire instances is doing anything, it's not appearing in bonfire notifications
- [ ] when looking up Mastodon actor by URL: `constraint error when attempting to insert struct: * bonfire_data_activity_pub_peer_ap_base_uri_index (unique_constraint)``
- [ ] issue with keys when doing a lookup: https://sentry.io/organizations/bonfire-networks/issues/3082272841/?project=5880694&query=is%3Aunresolved
- [ ] redir issue: https://sentry.io/organizations/bonfire-networks/issues/2932967804/?project=5880694&query=is%3Aunresolved
- [ ] 

## * working with caveats: 
- [ ] sometimes getting a contraint error when looking up a remote user on bonfire: `constraint error when attempting to insert struct: * ap_object__data____id_index (unique_constraint)` -> can't seem to write a broken test for this: https://github.com/bonfire-networks/bonfire_federate_activitypub/commit/b357404ad3d7153069f5c6d2e992646047c91d87#diff-4491e499af34e2d470e052379a18e1a678ed19d85a962dce8c12cc82184a51dfR95
- [ ] mastodon is not showing profile pic, bio, etc of bonfire profiles
- [ ] remote post created with a date of "52 years ago": https://bonfire.kiwi.mayel.space/post/0001H2GGT9ZFNTXD59A99SQJVT

**Comment by ZenKyma** [comment]
I would love to see bonfire to federate with funkwhale as well!

**Comment by mayel** [comment]
added to the list :) we want to federate all the things!

**Comment by ivanminutillo** [comment]
getting this error while federating with masto (when trying to follow from a mastodon user but seems a general error):

```

[error] : There was an unknown error. 
    (bonfire_ui_common 0.1.0) lib/error/error_view.ex:138: Bonfire.UI.Common.ErrorView.show_error/4
    (phoenix_template 1.0.4) lib/phoenix/template.ex:126: Phoenix.Template.render_to_iodata/4
    (phoenix 1.7.10) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
    (telemetry 1.2.1) /Users/ivan/Sites/bonfire-app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix 1.7.10) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
    (phoenix 1.7.10) lib/phoenix/endpoint/render_errors.ex:86: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
    (phoenix 1.7.10) lib/phoenix/endpoint/render_errors.ex:63: Phoenix.Endpoint.RenderErrors.__catch__/5
    (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4

[info] Sent 500 in 797ms
[debug] Converted error :undef to 500 response
[error] GenServer #PID<0.33244.0> terminating
** (UndefinedFunctionError) function HTTPSignatures.validate_cached/1 is undefined or private
    (http_signatures 0.1.1) HTTPSignatures.validate_cached(%Plug.Conn{adapter: {Bandit.HTTP1.Adapter, :...}, assigns: %{digest: "SHA-256=JnO2uZwqAS8xjoT9p9Y5WGwbQuRcUnVU0YmY4qJzLkg="}, body_params: %{"@context" => "https://www.w3.org/ns/activitystreams", "actor" => "https://social.coop/users/bernini", "id" => "https://social.coop/users/bernini#follows/470375/undo", "object" => %{"actor" => "https://social.coop/users/bernini", "id" => "https://social.coop/50cc5c27-7b3d-41db-b86a-dd61091c62e0", "object" => "https://bonfire-test.tunnelto.dev/pub/actors/ivan", "type" => "Follow"}, "type" => "Undo"}, cookies: %{}, halted: false, host: "bonfire-test.tunnelto.dev", method: "POST", owner: #PID<0.33244.0>, params: %{"@context" => "https://www.w3.org/ns/activitystreams", "actor" => "https://social.coop/users/bernini", "id" => "https://social.coop/users/bernini#follows/470375/undo", "object" => %{"actor" => "https://social.coop/users/bernini", "id" => "https://social.coop/50cc5c27-7b3d-41db-b86a-dd61091c62e0", "object" => "https://bonfire-test.tunnelto.dev/pub/actors/ivan", "type" => "Follow"}, "type" => "Undo", "username" => "ivan"}, path_info: ["pub", "actors", "ivan", "inbox"], path_params: %{"username" => "ivan"}, port: 80, private: %{Bonfire.Web.Router => [], :phoenix_endpoint => Bonfire.Web.Endpoint, :phoenix_router => Bonfire.Web.Router, :plug_session_fetch => #Function<1.76384852/1 in Plug.Session.fetch_session/1>, :before_send => [#Function<1.492364/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>, #Function<0.54455629/1 in Plug.Telemetry.call/2>], :phoenix_format => "json", :phoenix_request_logger => {"request_logger", "request_logger"}}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{}, req_headers: [{"fly-tracestate", ""}, {"fly-traceparent", "00-b340d582890215064108980f8b0a630a-8e17c9da3579af68-00"}, {"via", "1.1 fly.io"}, {"fly-request-id", "01HM6B1ZN80H9F07AC72Q23ZRN-arn"}, {"fly-region", "arn"}, {"x-forwarded-port", "443"}, {"fly-forwarded-port", "443"}, {"x-forwarded-ssl", "on"}, {"fly-forwarded-ssl", "on"}, {"x-forwarded-proto", "https"}, {"fly-forwarded-proto", "https"}, {"x-forwarded-for", "65.109.113.162, 213.188.198.72"}, {"fly-client-ip", "65.109.113.162"}, {"content-length", "367"}, {"x-request-start", "t=1705314942632309"}, {"signature", "keyId=\"https://social.coop/users/bernini#main-key\",algorithm=\"rsa-sha256\",headers=\"(request-target) host date digest content-type\",signature=\"tf6HybVSnYRD+ZCzjTJUeFDo/0TyF/nX7f43AUSlEL/Gh3BofNhOZ1fCPdz1eiv647si0E0KbqiOhkwLJaRxpnJduiA3xF9CBvaPBVy1/j2wXl9qCpVDEGYFGclqGmyB7cPdt9uff75bp4rI3hEdlaC285wv2865kMm5Ng/pcFlz8DVTT9i9n/sFvQWHcqwWXDs4pC0iq2XJ4k6kzQB5r6imrFrvvz0pTZ2OV3B7VwEw5vXjPxrLvu33MR4OuKWr3t+Po61+ziFw3VeQYgy7zS5I2tjSwit74Q10IYzEyBwSu8Wn/r3qmu9UA9b9glMPOODKnXfHlFXmBDVeMuaIew==\""}, {"content-type", "application/activity+json"}, {"digest", "SHA-256=JnO2uZwqAS8xjoT9p9Y5WGwbQuRcUnVU0YmY4qJzLkg="}, {"accept-encoding", "gzip"}, {"date", "Mon, 15 Jan 2024 10:35:42 GMT"}, {"host", "bonfire-test.tunnelto.dev"}, {"user-agent", "http.rb/5.1.1 (Mastodon/4.2.2; +https://social.coop/)"}, {"(request-target)", "post /pub/actors/ivan/inbox"}], request_path: "/pub/actors/ivan/inbox", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "F6p-589i4y65yzoAAImC"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil})
    (activity_pub 0.1.0) lib/web/plugs/http_signature_plug.ex:49: ActivityPub.Web.Plugs.HTTPSignaturePlug.call/2
    (bonfire 0.1.0-beta.3) Bonfire.Web.Router.signed_activity_pub_incoming/2
    (bonfire 0.1.0-beta.3) _build/dev/lib/bonfire/priv/extras/router_reverse.ex:2: Bonfire.Web.Router.__pipe_through12__/1
    (phoenix 1.7.10) lib/phoenix/router.ex:423: Phoenix.Router.__call__/5
    (bonfire 0.1.0-beta.3) lib/web/endpoint.ex:1: Bonfire.Web.Endpoint.plug_builder_call/2
    (bonfire 0.1.0-beta.3) lib/web/endpoint.ex:1: Bonfire.Web.Endpoint.call/2
    (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.1.2) lib/bandit/pipeline.ex:101: Bandit.Pipeline.call_plug/2
    (bandit 1.1.2) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
    (bandit 1.1.2) lib/bandit/http1/handler.ex:31: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.1.2) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.1.2) /Users/ivan/Sites/bonfire-app/deps/thousand_island/lib/thousand_island/handler.ex:411: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 5.2) gen_server.erl:1085: :gen_server.try_handle_continue/3
    (stdlib 5.2) gen_server.erl:995: :gen_server.loop/7
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.836>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.1580393547.2483027970.261797>, start_time: -576458369494907758, start_metadata: %{remote_port: 57539, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.1580393547.2483027970.261797>, parent_telemetry_span_context: #Reference<0.1580393547.2481455105.20450>}}}, %{opts: %{websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {Bonfire.Web.Endpoint, []}}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true, websocket_enabled: true}}
iex(localenv@MBP-di-ivan)11> 
```

**Comment by mayel** [comment]
moved to a wiki page: https://github.com/bonfire-networks/bonfire-app/wiki/Manual-federation-testing
