### ISSUE TITLE
Composer bug lists

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#492]
Some of these issues are not replicable, maybe they appear when there are 2 sockets connection open (because of the composer sticky component maybe ?) or maybe there's some bug introduced in mixing alpinejs with settings preferences

- [x] Remove unused props through all the composer components
- [x] Replace alpinejs with liveview.JS in composer
- [x] When clicking on a custom boundary the boundary name in the composer "TO" section is not updated correctly
- [x] When adding a boundary to the composer I got 
 ```
[error] GenServer #PID<0.7130.0> terminating
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %{"field" => "to_boundaries", "id" => "01GMGAGJ4JWYKQFW1226Q4J7XP"} of type Map. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
    (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
    (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
    (bonfire_boundaries 0.1.0) lib/web/components/set/boundary_items_live.sface:10: anonymous fn/4 in Bonfire.Boundaries.Web.BoundaryItemsLive."render (overridable 1)"/1
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (bonfire_boundaries 0.1.0) lib/web/components/set/boundary_items_live.sface:3: anonymous fn/2 in Bonfire.Boundaries.Web.BoundaryItemsLive."render (overridable 1)"/1
    (bonfire_boundaries 0.1.0) /opt/app/extensions/bonfire_boundaries/lib/web/components/set/set_boundaries_live.sface:25: Bonfire.Boundaries.Web.SetBoundariesLive.render/1
```
    
- [x] add a proper loader component when submitting a post
- [x] limit the media uploads fails when adding multiple together
- [x] improve UI for edit image options
- [x] after publishing a post, the composer should default to empty and close
- [x] When posting with images, the composer lags for several time before publishing
- [x] When closing the composer appears the alert, if I click on cancel, the composer get closed anyway
- [x] When in Focused layout, the blurred background doesnt close the composer modal when clicked
- [x] When selecting Focused | non blocking layout in the preference page, the composer continues to appear as the previous selected for some times (need to hard refresh a couple of times to switch) 
- [x]  The boundary selection should include a reference if advanced permissions are included (circles, boundaries, users apart from Public | local only | mention ) 
![image](https://user-images.githubusercontent.com/1852065/224740198-db28bee5-3925-494a-89d1-e81a772bddb3.png)
- [x] **Focused layout**: Sometimes clicking the reply button on an activity does not open the composer - need to click twice (see video) (https://www.loom.com/share/91eacba157144e99ace62168e5d97920)

**Comment by ivanminutillo** [comment]
all fixed :)
