### ISSUE TITLE
fix cases where the actor of remote activities isn't handled and gets replaced by `activitypub_fetcher`

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#724]
- [ ] author of something that was boosted
- [ ] identify other cases...

**Comment by ivanminutillo** [comment]
there's [this broken test](https://github.com/bonfire-networks/activity_pub/blob/develop/test/activity_pub/safety/signatures/signature_test.exs#L87) in signature_test.exs that may provide some hints on this issue. 
Instead of returning error when the user is not found, it creates a new activitypub_fetcher user...
Here some logs from the test to dig into it:

```[debug pid=<0.1494.0> ] [bonfire_federate_activitypub/lib/adapter/adapter_utils.ex:153@Bonfire.Federate.ActivityPub.AdapterUtils.get_character_by_username/1] not a user, check for any other character types: activitypub_fetcher ```
 
```
[error pid=<0.1494.0> ] Adapter did not find a local actor: :not_found
         (activity_pub 0.1.0) lib/actor.ex:107: ActivityPub.Actor.get/1
         (activity_pub 0.1.0) lib/utils.ex:261: anonymous fn/5 in ActivityPub.Utils.get_with_cache/4
         (activity_pub 0.1.0) lib/utils.ex:258: ActivityPub.Utils.get_with_cache/4
         (bonfire_federate_activitypub 0.1.0) lib/adapter/adapter.ex:365: Bonfire.Federate.ActivityPub.Adapter.get_or_create_service_actor/0
         (activity_pub 0.1.0) lib/safety/keys.ex:216: ActivityPub.Safety.Keys.make_signature/2
         (activity_pub 0.1.0) lib/safety/keys.ex:207: ActivityPub.Safety.Keys.maybe_add_sign_headers/3
         (activity_pub 0.1.0) lib/federator/fetcher.ex:285: ActivityPub.Federator.Fetcher.fetch_remote_object_from_id/2
         (activity_pub 0.1.0) lib/federator/fetcher.ex:124: ActivityPub.Federator.Fetcher.fetch_fresh_object_from_id/2
     
     [warning pid=<0.1494.0> ] nothing with username - activitypub_fetcher : {:error, :not_found}
         (activity_pub 0.1.0) lib/utils.ex:271: anonymous fn/5 in ActivityPub.Utils.get_with_cache/4
         (activity_pub 0.1.0) lib/utils.ex:258: ActivityPub.Utils.get_with_cache/4
         (bonfire_federate_activitypub 0.1.0) lib/adapter/adapter.ex:365: Bonfire.Federate.ActivityPub.Adapter.get_or_create_service_actor/0
         (activity_pub 0.1.0) lib/safety/keys.ex:216: ActivityPub.Safety.Keys.make_signature/2
         (activity_pub 0.1.0) lib/safety/keys.ex:207: ActivityPub.Safety.Keys.maybe_add_sign_headers/3
     
     [debug pid=<0.1494.0> ] SQL query: ok db=0ms source="bonfire_data_identity_account"
       SELECT count(b0."id") FROM "bonfire_data_identity_account" AS b0 
         (bonfire_me 0.1.0) lib/accounts/accounts.ex:648: Bonfire.Me.Accounts.is_first_account?/0
         (bonfire_me 0.1.0) lib/accounts/accounts.ex:137: Bonfire.Me.Accounts.do_signup/2
         (bonfire_me 0.1.0) lib/testing/fake.ex:17: Bonfire.Me.Fake.fake_account!/2
         (bonfire_me 0.1.0) lib/testing/fake.ex:45: Bonfire.Me.Fake.fake_user!/3
         (bonfire_federate_activitypub 0.1.0) lib/adapter/adapter.ex:370: Bonfire.Federate.ActivityPub.Adapter.get_or_create_service_actor/0
     
     [debug pid=<0.1494.0> ] [bonfire_me/lib/accounts/accounts.ex:151@Bonfire.Me.Accounts.do_signup/2] opts: [
       is_first_account: true,
       must_confirm?: false,
       params: %{
         credential: %{password: "7YFOGQHD6NBMNNCE"},
         email: %{email_address: "major.williamson@donnelly.org"}
       }
     ]
     
     [debug pid=<0.1494.0> ] [bonfire_me/lib/accounts/accounts.ex:159@Bonfire.Me.Accounts.do_signup/2] changeset: #Ecto.Changeset<
       action: nil,
       changes: %{
         id: "01HFECWFTX373DMG3Q408R4EAY",
         credential: #Ecto.Changeset<
           action: :insert,
           changes: %{
             password: "**redacted**",
             password_hash: "$pbkdf2-sha512$1$eezu2numL7UpGq.2Nykx5w$syA1g.0ZiC80Ni5FgWbMEF7Wo9PthnxVlgIDb7RqpJcaBz1H/niUlGFcCddlnfMlELUbP1T8OOcN5ssIRpvVLw"
           },
           errors: [],
           data: #Bonfire.Data.Identity.Credential<>,
           valid?: true
         >,
         email: #Ecto.Changeset<
           action: :insert,
           changes: %{
             email_address: "major.williamson@donnelly.org",
             confirmed_at: ~U[2023-11-17 10:23:06.122773Z]
           },
           errors: [],
           data: #Bonfire.Data.Identity.Email<>,
           valid?: true
         >,
         instance_admin: #Ecto.Changeset<
           action: :insert,
           changes: %{id: "01HFECWFTX373DMG3Q408R4EAY", is_instance_admin: false},
           errors: [],
           data: #Bonfire.Data.AccessControl.InstanceAdmin<>,
           valid?: true
         >
       },
       errors: [],
       data: #Bonfire.Data.Identity.Account<>,
       valid?: true
     >```
    
and so forth....

if this is the case I think this may also lead to slowing down bonfire perfornance when federation is turned on, because it basically create users everytime a remote user is not found ?

**Comment by ivanminutillo** [comment]
keep digging into it. if updating the test like
```
test "it returns error when user not found" do
      assert {:error, :not_found} = Signatures.refetch_public_key(make_fake_conn("https://404"))
    end
    ```
    
it does pass, but i wonder what is the reason why it still creates a activitypub_fetcher under the hood - is it done on purpose or not?

**Comment by mayel** [comment]
There's only one `activitypub_fetcher` (unique username and also id: `1ACT1V1TYPVBREM0TESFETCHER`)
