### ISSUE TITLE
Bug: promote account fails with error 

### ISSUE THREAD

**Issue by lawik** [bonfire-networks/bonfire-app#845]
easy, classic @ ca41fc65124e5113202724315c10abed3dc87547

Command: `just mix bonfire.user.admin.promote lawik`

I have logged the user in and given it that username. For the wrong username I get "User not found".

```
[error] SQL query: error db=6ms source="bonfire_data_access_control_encircle"
  INSERT INTO "bonfire_data_access_control_encircle" ("circle_id","subject_id","id") VALUES ('0ADM1NSVSERW1THSVPERP0WERS','01HNJ34DJ5ZGDYNEAGRJGCBVAB','01HNJ3AKZQWZEBT8ZSZF3304MW') 
    (bonfire_me 0.1.0) lib/users/users.ex:234: Bonfire.Me.Users.make_admin/1
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix/cli.ex:92: Mix.CLI.run_task/2
    /home/lawik/.asdf/installs/elixir/1.15.4-otp-26/bin/mix:2: (file)
    (elixir 1.15.4) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4

[os_mon] memory supervisor port (memsup): Erlang has closed
```

**Comment by mayel** [comment]
First user is automatically an admin, so the error might just be because of that?

**Comment by lawik** [comment]
oh, okay
