### ISSUE TITLE
Bug: Unable to start bonfire while using the recipe for coop-cloud

### ISSUE THREAD

**Issue by hl0dwig** [bonfire-networks/bonfire-app#853]
**Describe the bug**
After trying to deploy and start the app with abra, the app is crashing and try to restart without success.
This is what I can see with the `docker service logs --follow` command

```
19:29:34.938 [notice] Application bonfire exited: Bonfire.Application.start(:normal, []) returned an error: shutdown: failed to start child: Bonfire.Finch
** (EXIT) an exception was raised:
** (ArgumentError) scheme is required for url: 
(finch 0.17.0) lib/finch/request.ex:135: Finch.Request.parse_url/1
 (finch 0.17.0) lib/finch.ex:227: Finch.cast_binary_destination/1
 (finch 0.17.0) lib/finch.ex:200: anonymous fn/2 in Finch.pool_options!/1
 (stdlib 5.2) maps.erl:416: :maps.fold_1/4
 (finch 0.17.0) lib/finch.ex:160: Finch.start_link/1
 (stdlib 5.2) supervisor.erl:420: :supervisor.do_start_child_i/3
 (stdlib 5.2) supervisor.erl:406: :supervisor.do_start_child/2
 (stdlib 5.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
Kernel pid terminated (application_controller) ("{application_start_failure,bonfire,{{shutdown,{failed_to_start_child,'Elixir.Bonfire.Finch',{'EXIT',{#{message => <<\"scheme is required for url: \">>,'__struct__' => 'Elixir.ArgumentError','__exception__' => true},[{'Elixir.Finch.Request',parse_url,1,[{file,\"lib/finch/request.ex\"},{line,135}]},{'Elixir.Finch',cast_binary_destination,1,[{file,\"lib/finch.ex\"},{line,227}]},{'Elixir.Finch','-pool_options!/1-fun-0-',2,[{file,\"lib/finch.ex\"},{line,200}]},{maps,fold_1,4,[{file,\"maps.erl\"},{line,416}]},{'Elixir.Finch',start_link,1,[{file,\"lib/finch.ex\"},{line,160}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,420}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,406}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,390}]}]}}}},{'Elixir.Bonfire.Application',start,[normal,[]]}}}")
```

**To Reproduce**
Follow the steps from https://recipes.coopcloud.tech/bonfire

**Expected behavior**
App should start

**Bonfire environment (please complete the following information):**
- Running env: prod with docker image
- Running flavour: classic

**Comment by mayel** [comment]
Thanks for the report! Could you please try commenting `SENTRY_DSN=` in your .env file? If that works I'll fix the issue so it works even with an empty DSN.

**Comment by hl0dwig** [comment]
well thanks for this quick anwser @mayel I managed to deploy it ;)
but... now I'm facing another issue :p I'll create another ticket I guess!
